version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: test
          command: CI=true yarn test --maxWorkers=2