version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: test
          command: yarn test